mate-volume-control/src/gvc-mixer-control.c
g_strcmp0 on two NULLs gives 0, so the logic is preserved here
=> [1.8] init vars properly, use safer string compare function

data/icons/16x16/status/Makefile.am, data/icons/22x22/status/Makefile.am, data/icons/24x24/status/Makefile.am, data/icons/32x32/status/Makefile.am, data/icons/scalable/devices/Makefile.am, data/icons/scalable/status/Makefile.am
Test case:
1. Install the GTK3 version of mate-media.
2. Set icon theme to Adwaita.
3. Launch mate-volume-control.
4. See the missing icons on input volume slider.
=> Fix missing icons on GTK3 with custom icon theme

mate-volume-control/gvc-stream-status-icon.c
This fixes the background for GTK+ 3 themes which don't support mate-panel explicitly. Themes could still overwrite the background if they want in the usual way.
=> Don't remove slider background

mate-volume-control/gvc-channel-bar.c, mate-volume-control/gvc-stream-status-icon.c
Fixes https://github.com/mate-desktop/mate-media/issues/83.
The last commit is actually an optional improvement that shows the volume in the popup in the muted state.
=> Applet floating-point fix

mate-volume-control/gvc-stream-status-icon.c
Apparently something got broken in GtkStatusIcon in GTK+3, so auto-refresh on icon theme change doesn't work like it did in GTK+2 (and like it's promised in the docs). Well, do it manually then.
=> refresh tray icon on icon theme change

mate-volume-control/gvc-stream-status-icon.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_point
=> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

mate-volume-control/gvc-stream-status-icon.c
this adds some deprecated code but brings back the icon
it was lost for GTK+3 build here:
https://github.com/mate-desktop/mate-media/commit/0c558fac14266f8c18cfb8bc1d4669ed35868c2f#diff-411bda4b8f441c44b560abc7245dd33cR264
=> applet: restore icon for "Sound Preferences" menu item

mate-volume-control/gvc-mixer-dialog.c
The expected: the same look like before
This PR affects these items (in red):
=> gvc-mixer-dialog.c: avoid deprecated 'gtk_widget_override_font'

mate-volume-control/gvc-applet.c
Teradici PCoIP on Linux presently has audio output but no audio input.
PulseAudio creates a "monitor" input device for each output device. These
combine so that a microphone icon is displayed in the tray even though no
actual input device is present. It's misleading, so we created this patch to
avoid it.
=> Ignore PulseAudio "monitor" inputs when displaying mic icon

mate-volume-control/gvc-applet.c, mate-volume-control/gvc-combo-box.c, mate-volume-control/gvc-mixer-dialog.c, mate-volume-control/gvc-status-icon.c
Fixes cppcheck warnings:
```
[mate-volume-control/gvc-applet.c:118]: (error) syntax error
[mate-volume-control/gvc-applet.c:133]: (error) syntax error
[mate-volume-control/gvc-applet.c:184]: (error) syntax error
[mate-volume-control/gvc-applet.c:287]: (error) syntax error
[mate-volume-control/gvc-applet.c:290]: (error) syntax error
[mate-volume-control/gvc-combo-box.c:111]: (error) syntax error
[mate-volume-control/gvc-combo-box.c:309]: (error) syntax error
[mate-volume-control/gvc-combo-box.c:317]: (error) syntax error
[mate-volume-control/gvc-combo-box.c:428]: (error) syntax error
[mate-volume-control/gvc-mixer-dialog.c:793]: (error) syntax error
[mate-volume-control/gvc-status-icon.c:107]: (error) syntax error
[mate-volume-control/gvc-status-icon.c:122]: (error) syntax error …
```
=> mate-volume-control: Fix 'syntax error' detected with 'cppcheck'

mate-volume-control/gvc-level-bar.c, mate-volume-control/gvc-mixer-dialog.c, mate-volume-control/sound-theme-file-utils.c
Fixes 'cppcheck' warnings:
```
[mate-volume-control/gvc-level-bar.c:572]: (style) The scope of the variable 'by' can be reduced.
[mate-volume-control/gvc-level-bar.c:611]: (style) The scope of the variable 'bx' can be reduced.
[mate-volume-control/gvc-mixer-dialog.c:379]: (style) The scope of the variable 'swtch' can be reduced.
[mate-volume-control/gvc-mixer-dialog.c:534]: (style) The scope of the variable 'swtch' can be reduced.
[mate-volume-control/gvc-mixer-dialog.c:1891]: (style) The scope of the variable 'closure' can be reduced.
[mate-volume-control/sound-theme-file-utils.c:47]: (style) The scope of the variable 'data_dir' can be reduced.
```
=> mate-volume-control: reduce the scope of some variables

mate-volume-control/gvc-mixer-dialog.c
Fixes cppcheck warnings:
```
[mate-volume-control/gvc-mixer-dialog.c:379] -> [mate-volume-control/gvc-mixer-dialog.c:405]: (style) Local variable control shadows outer variable
[mate-volume-control/gvc-mixer-dialog.c:535] -> [mate-volume-control/gvc-mixer-dialog.c:586]: (style) Local variable control shadows outer variable
```
=> gvc-mixer-dialog: avoid declaration of same variable in different scope

configure.ac
The significant changes are:
* Disabling one of the targets wouldn't actually work, because there were typos in some variable names (hyphens rather than underscores).
* There were non-portable "==" expressions with test(1). These should be expressed as "=" for better portability (POSIX compliance).
I also changed other test expressions to make them idiomatic to configure (handle the possibility of a null string) and I set default values for these new options. (Those AC_ARG_ENABLE lines really need to be wrapped, but I didn't want to mix purely cosmetic alterations in this change set.)
=> configure.ac: fix typos in var names, portability fixes, etc.

.travis.yml, configure.ac
It removes --enable-more-warnings, since it is recommended to use
--enable-compile-warnings=maximum
=> Use WARN_CFLAGS which are only set with --enable-compiler-warnings

mate-volume-control/Makefile.am
Before PR:
Please test.
Edit: Note, only the panel-applet has this issue, menu of tray-applet looks good.
=> fix volume-panel-applet can not find mo file

configure.ac
there's no C++ code in this project
=> [1.22] build: drop MATE_CXX_WARNINGS

mate-volume-control/gvc-applet.c
Initialize the applet GktBox in the appropriate direction.
=> panel-applet: ensure speaker can be shown alongside or above mic

mate-volume-control/gvc-stream-applet-icon.c
Test: Show volume control bar
- Add `Volume Control` applet to Panel
- Click on `Volume Control` icon
Removed warning
```
gvc-stream-applet-icon.c:82:87: warning: implicit conversion from ‘MatePanelAppletOrient’ to ‘GtkOrientation’ [-Wenum-conversion]
82 |         gvc_channel_bar_set_orientation (GVC_CHANNEL_BAR (icon->priv->bar), icon->priv->orient);
|                                                                             ~~~~~~~~~~^~~~~~~~
```
=> gvc-stream-applet-icon: Remove enum-conversion warning

data/mate-volume-control.desktop.in.in
```
$ desktop-file-validate ./data/mate-volume-control.desktop
./data/mate-volume-control.desktop: hint: value item "Mixer" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: AudioVideo;Audio
./data/mate-volume-control.desktop: hint: value "AudioVideo;Mixer;Settings;HardwareSettings;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```
https://specifications.freedesktop.org/menu-spec/latest/apas02.html
=> Fix desktop file validation warnings

mate-volume-control/gvc-mixer-dialog.c
```
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
Fix the build warnings below:
```
gvc-mixer-dialog.c:1802:23: warning: comparison of integers of different signs: 'gint' (aka 'int') and 'unsigned long' [-Wsign-compare]
for (i = 0; i < G_N_ELEMENTS (tab_accel_keys); i++) {
~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gvc-mixer-dialog.c:2004:23: warning: comparison of integers of different signs: 'gint' (aka 'int') and 'unsigned long' [-Wsign-compare]
for (i = 0; i < G_N_ELEMENTS (tab_accel_keys); i++) {
~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> gvc-mixer-dialog: fix build warning -Wsign-compare

mate-volume-control/gvc-balance-bar.c, mate-volume-control/gvc-level-bar.c
```
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
Fix the build warnings below:
```
gvc-balance-bar.c:485:76: warning: implicit conversion loses floating-point precision: 'gdouble' (aka 'double') to 'gfloat' (aka 'float') [-Wimplicit-float-conversion]
mate_mixer_stream_control_set_balance (bar->priv->control, value);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ^~~~~
gvc-balance-bar.c:488:73: warning: implicit conversion loses floating-point precision: 'gdouble' (aka 'double') to 'gfloat' (aka 'float') [-Wimplicit-float-conversion]
mate_mixer_stream_control_set_fade (bar->priv->control, value);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> Fix warnings -Wfloat-conversion, -Wimplicit-float-conversion

mate-volume-control/sound-theme-file-utils.c
```
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
Fix the build warning below:
```
sound-theme-file-utils.c:195:33: warning: format string is not a string literal [-Wformat-nonliteral]
name = g_strdup_printf (pattern, sound_name);
^~~~~~~
```
=> sound-theme-file-utils: fix build warning -Wformat-nonliteral

mate-volume-control/gvc-stream-applet-icon.c
```
Direct leak of 7 byte(s) in 1 object(s) allocated from:
#0 0x7fd32d49693f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fd32beb11bf in g_malloc ../glib/gmem.c:106
#2 0x7fd32beb1502 in g_malloc_n ../glib/gmem.c:344
#3 0x7fd32bed3995 in g_strdup ../glib/gstrfuncs.c:364
#4 0x409bfa in gvc_stream_applet_icon_set_display_name /home/robert/builddir.gcc/mate-media/mate-volume-control/gvc-stream-applet-icon.c:504
#5 0x40ce8b in gvc_applet_init /home/robert/builddir.gcc/mate-media/mate-volume-control/gvc-applet.c:403
#6 0x7fd32bfe3623 in g_type_create_instance ../gobject/gtype.c:1929
#7 0x7fd32bfc8bd4 in g_object_new_internal ../gobject/gobject.c:1945
#8 0x7fd32bfc8170 in g_object_new_with_properties ../gobject/gobject.c:2114
#9 0x7fd32bfc7ef3 in g_object_new …
```
=> gvc-stream-applet-icon: fix memory leak

mate-volume-control/gvc-balance-bar.c
```
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
Fix the build warning below:
```
gvc-balance-bar.c:33:9: warning: macro is not used [-Wunused-macros]
#define BALANCE_BAR_STYLE                                       \
^
```
=> gvc-balance-bar: fix build warning -Wunused-macros

mate-volume-control/dialog-main.c, mate-volume-control/status-icon-main.c
```
status-icon-main.c:48:24: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
dialog-main.c:195:24: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
```
=> Fix build warnings about missing field initializer

mate-volume-control/gvc-channel-bar.c, mate-volume-control/gvc-channel-bar.h, mate-volume-control/gvc-mixer-dialog.c, mate-volume-control/gvc-stream-applet-icon.c, mate-volume-control/gvc-stream-status-icon.c
There is often a need for the user to increase the audio playback volume above
the volume level known as "100% volume".  While increasing the audio volume
above 100% can result in degraded audio quality, sometimes the audio was, for
example, originally recorded at an extremely low volume, and the user has no
other option to clearly hear the audio.  Unfortunately, most MATE applications
with volume controls do not allow the user to set the volume level above 100%.
For example, the main MATE Sound Preferences dialog lets you set the audio
volume beyond 100% (when possible), whereas the Volume Control Applet, Volume
Control status icon, and special "multimedia" volume control keys do not.  In
fact, if the user even tries to change the volume using any of the latter
methods, and the current …
=> Add setting for adjustment of audio volume above 100 per cent:  Part 2

mate-volume-control/gvc-channel-bar.c, mate-volume-control/gvc-stream-status-icon.c
Value of the variables when the volume is set to 100% (0 db):
- volume = normal = 65536
- volume_percent = 100
- decibel = 0
It reverts the commit b005276f2bb281b1bc2d1ef4ba18cdd43294d58f
=> gvc-stream-status-icon: fix a volume rounding error (101% -> 100%)

mate-volume-control/Makefile.am, mate-volume-control/applet-main.c, mate-volume-control/gvc-applet.c, mate-volume-control/org.mate.applets.GvcApplet.mate-panel-applet.desktop.in.in, mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service.in
*Wayland cannot use xembed/GtkPlug/GtkSocket so port to in-process. *The applet then works on wayland.
=> Applet: port to in-process for wayland support

.build.yml, configure.ac, mate-volume-control/Makefile.am, mate-volume-control/applet-main.c, mate-volume-control/gvc-applet.c, mate-volume-control/gvc-stream-applet-icon.c, mate-volume-control/org.mate.applets.GvcApplet.mate-panel-applet.desktop.in.in, mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service, mate-volume-control/org.mate.panel.applet.GvcAppletFactory.service.in
Position the slider correctly in wayland (all four panel orientations tested) and allow passing --disable-wayland and --disable-in-process together for non-wayland, out of process builds
=> position popup slider properly in wayland and make wayland optional

mate-volume-control/gvc-stream-applet-icon.c
*Set slider as the top layer not the bottom using gtk-layer-shell
*Fix https://github.com/mate-desktop/mate-media/issues/198
=> Wayland: fix slider rendering underneath fullscreen windows

mate-volume-control/gvc-applet.c
The method used out of process to enable scrolling on the icon without clicking on it to raise and lower volume does not work in-process, so set the event mask to enable scrolling directly when building in-process
=> in-process: enable scrolling on icon as in out of process builds

mate-volume-control/applet-main.c, mate-volume-control/gvc-applet.c, mate-volume-control/gvc-channel-bar.c, mate-volume-control/gvc-stream-applet-icon.c
When loaded as in-process applet, we must not call `textdomain()` or we will override mate-panel's text domain.  Instead, properly use gi18n-lib.h header that provides the same API but uses the compile-time `GETTEXT_PACKAGE` value for each call.
Fixes #203.
=> applet: Do not override the process' text domain

mate-volume-control/gvc-balance-bar.c, mate-volume-control/gvc-level-bar.c, mate-volume-control/gvc-stream-applet-icon.c, mate-volume-control/gvc-stream-status-icon.c
The `g_return*_if_fail()` calls should use `PREFIX_IS_TYPE_NAME` [1], which returns whether the given instance is of the right type, not `PREFIX_TYPE_NAME` [2], which checks whether the given instance if of the right type, warns if not, and returns the passed-in instance unchanged.
Using the wrong one means the returned value is the passed-in pointer, and thus passes the `g_return*_if_fail()` whenever the pointer is non-NULL, no matter whether it's of the right type or not.
A warning would still be emitted by `g_type_check_instance_cast()`, but the execution wouldn't get short-circuited.
[1] calls `g_type_check_instance_is_a()`
[2] calls `g_type_check_instance_cast()`
=> Fix various instance checks

mate-volume-control/gvc-sound-theme-chooser.c
```
gvc-sound-theme-chooser.c:462:15: error: implicit declaration of function ‘xmlParseFile’; did you mean ‘xmlSaveFile’? [-Werror=implicit-function-declaration]
462 |         doc = xmlParseFile (filename);
|               ^~~~~~~~~~~~
|               xmlSaveFile
gvc-sound-theme-chooser.c:462:13: warning: assignment to ‘xmlDocPtr’ {aka ‘struct _xmlDoc *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
462 |         doc = xmlParseFile (filename);
|             ^
```
Successful build with libxml-2.12.0 from fedora-rawhide at fedora build-server https://koji.fedoraproject.org/koji/taskinfo?taskID=109500185
https://src.fedoraproject.org/rpms/mate-media/blob/rawhide/f/mate-media.spec#_14
=> fix building with libxml 2.12.0

build-aux/meson_post_install.sh, data/icons/meson.build, data/meson.build, data/sounds/meson.build, man/meson.build, mate-volume-control/meson.build, meson.build, meson_options.txt, po/meson.build
```
meson setup _build --prefix=/usr -Din-process=true -Ddefault_library=both
ninja -C _build
DESTDIR=/tmp/meson_dir meson install -C _build
```
```
./autogen.sh --prefix=/usr --enable-in-process=yes
make
make install DESTDIR=/tmp/make_dir
```
```
[test@localhost mate-power-manager]$ find /tmp/make_dir/ | wc -l
489
[test@localhost mate-power-manager]$ find /tmp/meson_dir/ | wc -l
488
```
```meson``` does not provide ```libmate-volume-control-applet.la```, so the total number is one less, which is not a problem
=> add meson build support

mate-volume-control/gvc-stream-applet-icon.c
Checking for GDK_WINDOWING_WAYLAND breaks the wayland support when built with meson as it is not detected
=> meson: fix building wayland support

mate-volume-control/gvc-applet.c, mate-volume-control/gvc-stream-applet-icon.c
This is not working for the volume icon in notification area, it's only for the volume applet. Continuation of the idea of https://github.com/mate-desktop/mate-panel/pull/1474.
```css
.mate-panel-menu-bar .mate-volume-applet .menu-button:checked { background:yellow; }
```
=> Allow to theme volume applet
